name: mapbox_widget_layer
description: Custom Flutter Widgets on top of a Mapbox Map (package mapbox_gl). Exposes builders to reactively build widgets based on screen position, zoom, bearing, and tilt.
version: 0.1.0+2
homepage: https://github.com/dartclub/mapbox_widget_layer

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl: ^0.16.0
  turf: ^0.0.7
  pointer_interceptor: ^0.9.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
